version: '2'

services:

  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "dev"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "123456"
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306/tcp"
    restart: always
  
  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    links:
      - db
      - redis
    volumes:
      - ./app/demo:/mnt/demo
      - /Users/hundredlee/PHPStorm/Forchange/groups:/mnt/groups
      - /Users/hundredlee/PHPStorm/for_love:/mnt/for_love
    restart: always

  web:
    image: nginx:1.11.1
    ports:
      - "80:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./services/web/config:/etc/nginx/conf.d/
    restart: always

  redis:
    build:
      context: ./services/redis
      dockerfile: Dockerfile
    expose:
      - "6379/tcp"
    ports: 
      - "6379:6379"
    restart: always

volumes:
  db:
    driver: local